name: McAvatar
version: 0.1
main: mcavatar.McAvatar
api-version: 1.17
commands:
  bending:
    description: View stuff
    usage: "Usage: /<command> <view | assign | revoke> <player> [earth | fire | water | air]"
    permission: mcavatar.cli.bending
    permission-message: "You cannot use this command"
permissions:
  mcavatar.abilities.earth:
    description: Allows earthbending
    default: false
  mcavatar.abilities.fire:
    description: Allows firebending
    default: false
  mcavatar.cli.bending:
    description: Allows manipulation of players' bending abilities
    default: op
